; The installer's own text in each language Scoobert offers. makensis reads this file as UTF-8 because
; scripts/package-windows.ps1 passes /INPUTCHARSET UTF8. Button names in the text match the NSIS language files.

!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Spanish"
!insertmacro MUI_LANGUAGE "French"
!insertmacro MUI_LANGUAGE "German"
!insertmacro MUI_LANGUAGE "PortugueseBR"
!insertmacro MUI_LANGUAGE "Italian"
!insertmacro MUI_LANGUAGE "Russian"
!insertmacro MUI_LANGUAGE "Japanese"
!insertmacro MUI_LANGUAGE "Korean"
!insertmacro MUI_LANGUAGE "SimpChinese"

; The code Scoobert reads from language.txt.
LangString LangCode ${LANG_ENGLISH} "en"
LangString LangCode ${LANG_SPANISH} "es"
LangString LangCode ${LANG_FRENCH} "fr"
LangString LangCode ${LANG_GERMAN} "de"
LangString LangCode ${LANG_PORTUGUESEBR} "pt-BR"
LangString LangCode ${LANG_ITALIAN} "it"
LangString LangCode ${LANG_RUSSIAN} "ru"
LangString LangCode ${LANG_JAPANESE} "ja"
LangString LangCode ${LANG_KOREAN} "ko"
LangString LangCode ${LANG_SIMPCHINESE} "zh-Hans"

LangString WelcomeTitle ${LANG_ENGLISH} "Install Scoobert"
LangString WelcomeTitle ${LANG_SPANISH} "Instalar Scoobert"
LangString WelcomeTitle ${LANG_FRENCH} "Installer Scoobert"
LangString WelcomeTitle ${LANG_GERMAN} "Scoobert installieren"
LangString WelcomeTitle ${LANG_PORTUGUESEBR} "Instalar o Scoobert"
LangString WelcomeTitle ${LANG_ITALIAN} "Installa Scoobert"
LangString WelcomeTitle ${LANG_RUSSIAN} "Установка Scoobert"
LangString WelcomeTitle ${LANG_JAPANESE} "Scoobert のインストール"
LangString WelcomeTitle ${LANG_KOREAN} "Scoobert 설치"
LangString WelcomeTitle ${LANG_SIMPCHINESE} "安装 Scoobert"

LangString WelcomeText ${LANG_ENGLISH} "Scoobert is a coding assistant that runs AI models on your own computer.$\r$\n$\r$\nIt installs for your Windows account only, so you don't need an administrator password.$\r$\n$\r$\nSelect Next to continue."
LangString WelcomeText ${LANG_SPANISH} "Scoobert es un asistente de programación que ejecuta modelos de IA en tu propio equipo.$\r$\n$\r$\nSe instala solo para tu cuenta de Windows, así que no necesitas una contraseña de administrador.$\r$\n$\r$\nSelecciona Siguiente para continuar."
LangString WelcomeText ${LANG_FRENCH} "Scoobert est un assistant de programmation qui exécute des modèles d'IA sur votre propre ordinateur.$\r$\n$\r$\nIl s'installe uniquement pour votre compte Windows : aucun mot de passe administrateur n'est nécessaire.$\r$\n$\r$\nSélectionnez Suivant pour continuer."
LangString WelcomeText ${LANG_GERMAN} "Scoobert ist ein Programmierassistent, der KI-Modelle auf deinem eigenen Computer ausführt.$\r$\n$\r$\nScoobert wird nur für dein Windows-Konto installiert, daher brauchst du kein Administratorkennwort.$\r$\n$\r$\nWähle Weiter, um fortzufahren."
LangString WelcomeText ${LANG_PORTUGUESEBR} "O Scoobert é um assistente de programação que executa modelos de IA no seu próprio computador.$\r$\n$\r$\nEle é instalado só para a sua conta do Windows, então você não precisa de senha de administrador.$\r$\n$\r$\nSelecione Próximo para continuar."
LangString WelcomeText ${LANG_ITALIAN} "Scoobert è un assistente di programmazione che esegue modelli di IA sul tuo computer.$\r$\n$\r$\nSi installa solo per il tuo account Windows, quindi non serve una password di amministratore.$\r$\n$\r$\nSeleziona Avanti per continuare."
LangString WelcomeText ${LANG_RUSSIAN} "Scoobert — помощник программиста, который запускает модели ИИ на вашем компьютере.$\r$\n$\r$\nОн устанавливается только для вашей учётной записи Windows, поэтому пароль администратора не нужен.$\r$\n$\r$\nНажмите «Далее», чтобы продолжить."
LangString WelcomeText ${LANG_JAPANESE} "Scoobert は、AI モデルをお使いのコンピューター上で実行するコーディングアシスタントです。$\r$\n$\r$\nお使いの Windows アカウントにのみインストールされるため、管理者パスワードは不要です。$\r$\n$\r$\n続けるには [次へ] を選択してください。"
LangString WelcomeText ${LANG_KOREAN} "Scoobert는 AI 모델을 사용자의 컴퓨터에서 실행하는 코딩 도우미입니다.$\r$\n$\r$\n현재 Windows 계정에만 설치되므로 관리자 암호가 필요하지 않습니다.$\r$\n$\r$\n계속하려면 [다음]을 선택하세요."
LangString WelcomeText ${LANG_SIMPCHINESE} "Scoobert 是一个在你自己的电脑上运行 AI 模型的编程助手。$\r$\n$\r$\n它只为你的 Windows 账户安装，因此不需要管理员密码。$\r$\n$\r$\n选择“下一步”继续。"

LangString DirectoryText ${LANG_ENGLISH} "Scoobert will be installed in the folder below. To put it somewhere else, such as on another drive, select Browse."
LangString DirectoryText ${LANG_SPANISH} "Scoobert se instalará en la carpeta de abajo. Para ponerlo en otro lugar, como otra unidad, selecciona Examinar."
LangString DirectoryText ${LANG_FRENCH} "Scoobert sera installé dans le dossier ci-dessous. Pour le placer ailleurs, par exemple sur un autre disque, sélectionnez Parcourir."
LangString DirectoryText ${LANG_GERMAN} "Scoobert wird im folgenden Ordner installiert. Um Scoobert woanders abzulegen, etwa auf einem anderen Laufwerk, wähle Durchsuchen."
LangString DirectoryText ${LANG_PORTUGUESEBR} "O Scoobert será instalado na pasta abaixo. Para colocá-lo em outro lugar, como outra unidade, selecione Procurar."
LangString DirectoryText ${LANG_ITALIAN} "Scoobert verrà installato nella cartella qui sotto. Per metterlo altrove, ad esempio su un'altra unità, seleziona Sfoglia."
LangString DirectoryText ${LANG_RUSSIAN} "Scoobert будет установлен в папку ниже. Чтобы выбрать другое место, например другой диск, нажмите «Обзор»."
LangString DirectoryText ${LANG_JAPANESE} "Scoobert は次のフォルダーにインストールされます。別のドライブなど別の場所に置くには、[参照] を選択してください。"
LangString DirectoryText ${LANG_KOREAN} "Scoobert는 아래 폴더에 설치됩니다. 다른 드라이브 등 다른 위치에 두려면 [찾아보기]를 선택하세요."
LangString DirectoryText ${LANG_SIMPCHINESE} "Scoobert 将安装到下面的文件夹。要放到其他位置（例如另一个驱动器），请选择“浏览”。"

LangString FinishTitle ${LANG_ENGLISH} "Scoobert is installed"
LangString FinishTitle ${LANG_SPANISH} "Scoobert está instalado"
LangString FinishTitle ${LANG_FRENCH} "Scoobert est installé"
LangString FinishTitle ${LANG_GERMAN} "Scoobert ist installiert"
LangString FinishTitle ${LANG_PORTUGUESEBR} "O Scoobert foi instalado"
LangString FinishTitle ${LANG_ITALIAN} "Scoobert è installato"
LangString FinishTitle ${LANG_RUSSIAN} "Scoobert установлен"
LangString FinishTitle ${LANG_JAPANESE} "Scoobert がインストールされました"
LangString FinishTitle ${LANG_KOREAN} "Scoobert가 설치되었습니다"
LangString FinishTitle ${LANG_SIMPCHINESE} "Scoobert 已安装"

LangString FinishText ${LANG_ENGLISH} "You can open Scoobert from its shortcut on the desktop or in the Start menu.$\r$\n$\r$\nTo remove it later, open Settings in Scoobert and select Uninstall, or use Installed apps in Windows Settings."
LangString FinishText ${LANG_SPANISH} "Puedes abrir Scoobert desde su acceso directo en el escritorio o en el menú Inicio.$\r$\n$\r$\nPara quitarlo más adelante, abre la configuración de Scoobert y desinstálalo desde ahí, o usa Aplicaciones instaladas en la Configuración de Windows."
LangString FinishText ${LANG_FRENCH} "Vous pouvez ouvrir Scoobert depuis son raccourci sur le bureau ou dans le menu Démarrer.$\r$\n$\r$\nPour le supprimer plus tard, désinstallez-le depuis les paramètres de Scoobert, ou utilisez Applications installées dans les Paramètres Windows."
LangString FinishText ${LANG_GERMAN} "Du kannst Scoobert über die Verknüpfung auf dem Desktop oder im Startmenü öffnen.$\r$\n$\r$\nUm Scoobert später zu entfernen, deinstalliere es in den Einstellungen von Scoobert oder nutze „Installierte Apps“ in den Windows-Einstellungen."
LangString FinishText ${LANG_PORTUGUESEBR} "Você pode abrir o Scoobert pelo atalho na área de trabalho ou no menu Iniciar.$\r$\n$\r$\nPara removê-lo depois, desinstale-o nas configurações do Scoobert ou use Aplicativos instalados nas Configurações do Windows."
LangString FinishText ${LANG_ITALIAN} "Puoi aprire Scoobert dal suo collegamento sul desktop o nel menu Start.$\r$\n$\r$\nPer rimuoverlo in seguito, disinstallalo dalle impostazioni di Scoobert oppure usa App installate nelle Impostazioni di Windows."
LangString FinishText ${LANG_RUSSIAN} "Scoobert можно открыть с помощью ярлыка на рабочем столе или в меню «Пуск».$\r$\n$\r$\nЧтобы удалить его позже, сделайте это в настройках Scoobert или в разделе «Установленные приложения» параметров Windows."
LangString FinishText ${LANG_JAPANESE} "Scoobert はデスクトップまたはスタート メニューのショートカットから開けます。$\r$\n$\r$\n後で削除するには、Scoobert の設定からアンインストールするか、Windows の設定の [インストールされているアプリ] を使用してください。"
LangString FinishText ${LANG_KOREAN} "바탕 화면이나 시작 메뉴의 바로 가기로 Scoobert를 열 수 있습니다.$\r$\n$\r$\n나중에 제거하려면 Scoobert 설정에서 제거하거나 Windows 설정의 [설치된 앱]을 사용하세요."
LangString FinishText ${LANG_SIMPCHINESE} "你可以通过桌面或“开始”菜单中的快捷方式打开 Scoobert。$\r$\n$\r$\n以后要删除它，请在 Scoobert 的设置中卸载，或使用 Windows 设置中的“已安装的应用”。"

LangString FinishRun ${LANG_ENGLISH} "Open Scoobert now"
LangString FinishRun ${LANG_SPANISH} "Abrir Scoobert ahora"
LangString FinishRun ${LANG_FRENCH} "Ouvrir Scoobert maintenant"
LangString FinishRun ${LANG_GERMAN} "Scoobert jetzt öffnen"
LangString FinishRun ${LANG_PORTUGUESEBR} "Abrir o Scoobert agora"
LangString FinishRun ${LANG_ITALIAN} "Apri Scoobert ora"
LangString FinishRun ${LANG_RUSSIAN} "Открыть Scoobert"
LangString FinishRun ${LANG_JAPANESE} "Scoobert を今すぐ開く"
LangString FinishRun ${LANG_KOREAN} "지금 Scoobert 열기"
LangString FinishRun ${LANG_SIMPCHINESE} "立即打开 Scoobert"

LangString FolderError ${LANG_ENGLISH} "Windows does not let Scoobert install in that folder without an administrator. Pick a folder inside your own user folder, or keep the one Scoobert suggested."
LangString FolderError ${LANG_SPANISH} "Windows no permite que Scoobert se instale en esa carpeta sin un administrador. Elige una carpeta dentro de tu carpeta de usuario o deja la que sugirió Scoobert."
LangString FolderError ${LANG_FRENCH} "Windows n'autorise pas Scoobert à s'installer dans ce dossier sans administrateur. Choisissez un dossier dans votre dossier utilisateur, ou gardez celui que Scoobert propose."
LangString FolderError ${LANG_GERMAN} "Windows lässt Scoobert ohne Administrator nicht in diesem Ordner installieren. Wähle einen Ordner in deinem Benutzerordner oder behalte den Ordner, den Scoobert vorschlägt."
LangString FolderError ${LANG_PORTUGUESEBR} "O Windows não deixa o Scoobert ser instalado nessa pasta sem um administrador. Escolha uma pasta dentro da sua pasta de usuário ou mantenha a que o Scoobert sugeriu."
LangString FolderError ${LANG_ITALIAN} "Windows non consente a Scoobert di installarsi in quella cartella senza un amministratore. Scegli una cartella nella tua cartella utente oppure mantieni quella suggerita da Scoobert."
LangString FolderError ${LANG_RUSSIAN} "Windows не разрешает установить Scoobert в эту папку без прав администратора. Выберите папку внутри своей папки пользователя или оставьте ту, которую предложил Scoobert."
LangString FolderError ${LANG_JAPANESE} "Windows では、管理者の許可なしにこのフォルダーへ Scoobert をインストールできません。ユーザー フォルダー内のフォルダーを選ぶか、Scoobert が提案したフォルダーのままにしてください。"
LangString FolderError ${LANG_KOREAN} "Windows에서는 관리자 권한 없이 이 폴더에 Scoobert를 설치할 수 없습니다. 사용자 폴더 안의 폴더를 선택하거나 Scoobert가 제안한 폴더를 그대로 사용하세요."
LangString FolderError ${LANG_SIMPCHINESE} "没有管理员权限时，Windows 不允许将 Scoobert 安装到该文件夹。请选择你自己的用户文件夹中的文件夹，或保留 Scoobert 建议的文件夹。"

LangString UnConfirmText ${LANG_ENGLISH} "Scoobert will be removed from this folder. Your projects and their notes are never touched."
LangString UnConfirmText ${LANG_SPANISH} "Scoobert se quitará de esta carpeta. Tus proyectos y sus notas no se tocan."
LangString UnConfirmText ${LANG_FRENCH} "Scoobert sera supprimé de ce dossier. Vos projets et leurs notes ne sont jamais touchés."
LangString UnConfirmText ${LANG_GERMAN} "Scoobert wird aus diesem Ordner entfernt. Deine Projekte und ihre Notizen bleiben unberührt."
LangString UnConfirmText ${LANG_PORTUGUESEBR} "O Scoobert será removido desta pasta. Seus projetos e as notas deles nunca são alterados."
LangString UnConfirmText ${LANG_ITALIAN} "Scoobert verrà rimosso da questa cartella. I tuoi progetti e le loro note non vengono mai toccati."
LangString UnConfirmText ${LANG_RUSSIAN} "Scoobert будет удалён из этой папки. Ваши проекты и их заметки не затрагиваются."
LangString UnConfirmText ${LANG_JAPANESE} "Scoobert をこのフォルダーから削除します。プロジェクトとそのノートには一切触れません。"
LangString UnConfirmText ${LANG_KOREAN} "이 폴더에서 Scoobert를 제거합니다. 프로젝트와 프로젝트의 노트는 건드리지 않습니다."
LangString UnConfirmText ${LANG_SIMPCHINESE} "将从此文件夹中删除 Scoobert。你的项目及其笔记不会被改动。"

LangString UnComponentsText ${LANG_ENGLISH} "Choose what else to remove. Anything you leave checked off stays, so a reinstall continues where you left off."
LangString UnComponentsText ${LANG_SPANISH} "Elige qué más quitar. Lo que dejes sin marcar se conserva, así que al reinstalar continúas donde lo dejaste."
LangString UnComponentsText ${LANG_FRENCH} "Choisissez ce que vous voulez supprimer en plus. Ce que vous laissez décoché est conservé, et une réinstallation reprend là où vous en étiez."
LangString UnComponentsText ${LANG_GERMAN} "Wähle, was zusätzlich entfernt werden soll. Was du nicht ankreuzt, bleibt erhalten, sodass eine Neuinstallation dort weitermacht, wo du aufgehört hast."
LangString UnComponentsText ${LANG_PORTUGUESEBR} "Escolha o que mais remover. O que você deixar desmarcado fica, então uma reinstalação continua de onde você parou."
LangString UnComponentsText ${LANG_ITALIAN} "Scegli cos'altro rimuovere. Ciò che lasci deselezionato resta, così una reinstallazione riprende da dove avevi lasciato."
LangString UnComponentsText ${LANG_RUSSIAN} "Выберите, что ещё удалить. Всё, что не отмечено, останется, и после переустановки можно продолжить с того же места."
LangString UnComponentsText ${LANG_JAPANESE} "ほかに削除するものを選んでください。チェックを付けなかったものは残るため、再インストールすると前回の続きから使えます。"
LangString UnComponentsText ${LANG_KOREAN} "추가로 제거할 항목을 선택하세요. 선택하지 않은 항목은 남아 있으므로 다시 설치하면 이전 상태에서 이어서 사용할 수 있습니다."
LangString UnComponentsText ${LANG_SIMPCHINESE} "选择还要删除的内容。未勾选的内容会保留，重新安装后可以从上次的进度继续。"

LangString UnAppDesc ${LANG_ENGLISH} "The Scoobert program, its shortcuts, and its saved prompt caches."
LangString UnAppDesc ${LANG_SPANISH} "El programa Scoobert, sus accesos directos y sus cachés de prompts guardados."
LangString UnAppDesc ${LANG_FRENCH} "Le programme Scoobert, ses raccourcis et ses caches de prompts enregistrés."
LangString UnAppDesc ${LANG_GERMAN} "Das Programm Scoobert, seine Verknüpfungen und seine gespeicherten Prompt-Caches."
LangString UnAppDesc ${LANG_PORTUGUESEBR} "O programa Scoobert, seus atalhos e seus caches de prompts salvos."
LangString UnAppDesc ${LANG_ITALIAN} "Il programma Scoobert, i suoi collegamenti e le sue cache dei prompt salvati."
LangString UnAppDesc ${LANG_RUSSIAN} "Программа Scoobert, её ярлыки и сохранённые кэши промптов."
LangString UnAppDesc ${LANG_JAPANESE} "Scoobert のプログラム、ショートカット、保存済みプロンプトのキャッシュ。"
LangString UnAppDesc ${LANG_KOREAN} "Scoobert 프로그램, 바로 가기, 저장된 프롬프트 캐시."
LangString UnAppDesc ${LANG_SIMPCHINESE} "Scoobert 程序、它的快捷方式和已保存的提示缓存。"

LangString UnDataName ${LANG_ENGLISH} "Settings and conversations"
LangString UnDataName ${LANG_SPANISH} "Configuración y conversaciones"
LangString UnDataName ${LANG_FRENCH} "Paramètres et conversations"
LangString UnDataName ${LANG_GERMAN} "Einstellungen und Unterhaltungen"
LangString UnDataName ${LANG_PORTUGUESEBR} "Configurações e conversas"
LangString UnDataName ${LANG_ITALIAN} "Impostazioni e conversazioni"
LangString UnDataName ${LANG_RUSSIAN} "Настройки и разговоры"
LangString UnDataName ${LANG_JAPANESE} "設定と会話"
LangString UnDataName ${LANG_KOREAN} "설정 및 대화"
LangString UnDataName ${LANG_SIMPCHINESE} "设置和对话"

LangString UnDataDesc ${LANG_ENGLISH} "Your project list, settings, and past conversations. Project notes stay in your projects."
LangString UnDataDesc ${LANG_SPANISH} "Tu lista de proyectos, la configuración y las conversaciones anteriores. Las notas de los proyectos se quedan en tus proyectos."
LangString UnDataDesc ${LANG_FRENCH} "Votre liste de projets, vos paramètres et vos conversations passées. Les notes des projets restent dans vos projets."
LangString UnDataDesc ${LANG_GERMAN} "Deine Projektliste, Einstellungen und bisherigen Unterhaltungen. Projektnotizen bleiben in deinen Projekten."
LangString UnDataDesc ${LANG_PORTUGUESEBR} "Sua lista de projetos, as configurações e as conversas anteriores. As notas dos projetos ficam nos seus projetos."
LangString UnDataDesc ${LANG_ITALIAN} "L'elenco dei progetti, le impostazioni e le conversazioni passate. Le note dei progetti restano nei tuoi progetti."
LangString UnDataDesc ${LANG_RUSSIAN} "Список проектов, настройки и прошлые разговоры. Заметки проектов остаются в ваших проектах."
LangString UnDataDesc ${LANG_JAPANESE} "プロジェクトの一覧、設定、過去の会話。プロジェクトのノートはプロジェクトに残ります。"
LangString UnDataDesc ${LANG_KOREAN} "프로젝트 목록, 설정, 이전 대화. 프로젝트 노트는 프로젝트에 그대로 남습니다."
LangString UnDataDesc ${LANG_SIMPCHINESE} "你的项目列表、设置和以往的对话。项目笔记保留在你的项目中。"

LangString UnModelsName ${LANG_ENGLISH} "Downloaded models (about $R3 GB)"
LangString UnModelsName ${LANG_SPANISH} "Modelos descargados (unos $R3 GB)"
LangString UnModelsName ${LANG_FRENCH} "Modèles téléchargés (environ $R3 Go)"
LangString UnModelsName ${LANG_GERMAN} "Heruntergeladene Modelle (etwa $R3 GB)"
LangString UnModelsName ${LANG_PORTUGUESEBR} "Modelos baixados (cerca de $R3 GB)"
LangString UnModelsName ${LANG_ITALIAN} "Modelli scaricati (circa $R3 GB)"
LangString UnModelsName ${LANG_RUSSIAN} "Загруженные модели (около $R3 ГБ)"
LangString UnModelsName ${LANG_JAPANESE} "ダウンロードしたモデル (約 $R3 GB)"
LangString UnModelsName ${LANG_KOREAN} "다운로드한 모델 (약 $R3GB)"
LangString UnModelsName ${LANG_SIMPCHINESE} "已下载的模型（约 $R3 GB）"

LangString UnModelsDesc ${LANG_ENGLISH} "The Qwen models Scoobert downloaded to your models folder. Downloading them again takes a while."
LangString UnModelsDesc ${LANG_SPANISH} "Los modelos Qwen que Scoobert descargó en tu carpeta de modelos. Volver a descargarlos lleva un rato."
LangString UnModelsDesc ${LANG_FRENCH} "Les modèles Qwen que Scoobert a téléchargés dans votre dossier de modèles. Les télécharger de nouveau prend un moment."
LangString UnModelsDesc ${LANG_GERMAN} "Die Qwen-Modelle, die Scoobert in deinen Modellordner heruntergeladen hat. Sie erneut herunterzuladen dauert eine Weile."
LangString UnModelsDesc ${LANG_PORTUGUESEBR} "Os modelos Qwen que o Scoobert baixou para a sua pasta de modelos. Baixá-los de novo leva um tempo."
LangString UnModelsDesc ${LANG_ITALIAN} "I modelli Qwen che Scoobert ha scaricato nella cartella dei modelli. Scaricarli di nuovo richiede un po' di tempo."
LangString UnModelsDesc ${LANG_RUSSIAN} "Модели Qwen, которые Scoobert загрузил в вашу папку моделей. Повторная загрузка займёт время."
LangString UnModelsDesc ${LANG_JAPANESE} "Scoobert がモデル フォルダーにダウンロードした Qwen モデル。もう一度ダウンロードするには時間がかかります。"
LangString UnModelsDesc ${LANG_KOREAN} "Scoobert가 모델 폴더에 다운로드한 Qwen 모델. 다시 다운로드하려면 시간이 걸립니다."
LangString UnModelsDesc ${LANG_SIMPCHINESE} "Scoobert 下载到你的模型文件夹中的 Qwen 模型。重新下载需要一些时间。"
